### ISSUE TITLE
onActivityResult not called in fragment

### ISSUE THREAD

**Issue by DJafari** [fingerlinks/Navigator#3]
when i build a activity in fragment, `onActivityResult` never called, because you call `startActivityForResult` from activity, how can solved this problem ?

thanks

**Comment by rebus007** [comment]
Hi, when you use startActivityForResult, you must to override onActivityResult in parent activity and pass return values to your fragment, like this:

```
Fragment fragment = getSupportFragmentManager().findFragmentById(R.id.container);
fragment.onActivityResult(requestCode, resultCode, data);
```
Cheers
