### ISSUE TITLE
goBackToSpecificPoint(TAG) does not work

### ISSUE THREAD

**Issue by aromal-sasidharan** [fingerlinks/Navigator#5]
**The util function goBackToSpecificPoint(TAG) does not seems working or am i doing something wrong? Please help!**
# 

```

if (    Navigator.with(tTestActivity.this).utils().canGoBackToSpecificPoint
           (SecondTestFragment.class.getName(), R.id.container, supportFragmentManager)){ // TRUE

// The above condition returns TRUE



// but the following code does not work     
Navigator.with(tTestActivity.this).utils().goBackToSpecificPoint(SecondTestFragment.class.getName().simpleName)

}
```

**Comment by rebus007** [comment]
You can post the complete Navigator implementation?
First question, when you commit a new fragment you add the fragment at the backstack?
Cheers

**Comment by aromal-sasidharan** [comment]
Yes i added the fragment to backstack.

**Comment by rebus007** [comment]
Ok, just a question, the "TAG" is a constant or the class name of your Fragment?
Cheers
