### ISSUE TITLE
TextView visibility not updated

### ISSUE THREAD

**Issue by rubix-eric** [fingerlinks/Navigator#6]
I need your help.

I am using the Navigator to create one activity, and multiple fragments. The application is essentially a decision tree built in XML files.

The fragment layout contains several TextView and the fragments are generated on an OnClick event of a ListView control entries.

My issue is that when a Fragment is created, I update the TextView visibility based on several conditions. Even if I set the visibility to View.INVISIBLE or View.GONE, the TextView visibility is not changed when running the application. Same thing if I try to set the text of the TextView to an empty string (it keeps the last string that was set).

Basically, the main activity class is:

```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main_activity);
        setSupportActionBar((Toolbar) findViewById(R.id.toolbar));

        Bundle bundle = new Bundle();

        Fragment fragment = new MainFragment();
        Navigator.with(MainActivity.this)
                .build() //Enter in navigation mode
                .goTo(fragment, bundle, R.id.container)
                .tag("HOME_FRAGMENT")
                .addToBackStack() //add backstack
                .animation()
                .add() //CommitType
                .commit(); //commit operation
    }
```

In my main fragment view, the new generated Fragments when the user clicks on a ListView entries is as follows:

```
Navigator.with(getActivity())
                    .build()
                    .goTo(MainFragment.class.getName(), bundle, R.id.container)
                    .addToBackStack()
                    .tag("fragment_" + numFragment)
                    .animation()
                    .add()
                    .commit();

            numFragment++;
```

The visibility of each TextView is done in the OnCreateView function override.

Can you help me with that?

**Comment by rebus007** [comment]
This is not exactly a Navigator bug, I do not understand what you mean...
Cheers
